### ISSUE TITLE
CU: Cargar archivo de excel no guarda correctamente carácteres especiales como 'Ñ'

### ISSUE THREAD

**Issue by jdjuan** [ditsas/cet#1]
En la interfaz de Captura.html se puede subir un archivo de excel con información.
Los carácteres especiales como la 'ñ' no son correctamente almacenados en la base de datos. 

Ejemplo: Tercero con número de identificación: 1047420009

![image](https://cloud.githubusercontent.com/assets/3171900/14711242/33f6ed78-079e-11e6-87a4-24c9b73d57f4.png)

**Comment by wilesna25** [comment]
Confirmo recibido

**Comment by wilesna25** [comment]
Recibido, en el momento tengo 3 archivos para hacer push pero no los he
subido porque hay otro 2 por aparte q creo que de irian también en el push.
 La wiki me pareció súper por lo que esta todo l que se ha mencionado
unificado, la leí toda.
Juan, ahora después de lasn2 le escribo para comentarle el error que le
mencioné, gracias.
